# Generated by Django 6.0.3 on 2026-05-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedistockCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_categories',
                'ordering': ['category_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockDepartment',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('department_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_departments',
                'ordering': ['department_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockGoodsReceipt',
            fields=[
                ('gr_id', models.AutoField(primary_key=True, serialize=False)),
                ('gr_no', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_by', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_goods_receipts',
                'ordering': ['-gr_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockGoodsReceiptItem',
            fields=[
                ('gr_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_item_id', models.IntegerField(blank=True, null=True)),
                ('qty_ordered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_goods_receipt_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockInventoryBalance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_inventory_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_locations',
                'ordering': ['location_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=100)),
                ('period_type', models.CharField(max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('generated_by', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_reports',
                'ordering': ['-report_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockSupplyBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_supply_batches',
                'ordering': ['-batch_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockSupplyItem',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('supply_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_name', models.CharField(max_length=255)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_supply_items',
                'ordering': ['supply_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockSupplyRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_no', models.CharField(max_length=255)),
                ('source_module', models.CharField(max_length=100)),
                ('requested_by_user_id', models.IntegerField(blank=True, null=True)),
                ('requested_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_supply_requests',
                'ordering': ['-request_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockSupplyRequestItem',
            fields=[
                ('request_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('qty_requested', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_approved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_dispensed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_supply_request_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_datetime', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('source_module', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_transactions',
                'ordering': ['-transaction_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_units',
                'ordering': ['unit_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockVCartItem',
            fields=[
                ('supply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supply_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_count', models.BigIntegerField(blank=True, null=True)),
                ('total_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nearest_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_v_cart_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockVExpiryAlert',
            fields=[
                ('batch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supply_id', models.IntegerField(blank=True, null=True)),
                ('supply_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_on_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('days_remaining', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_v_expiry_alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockVLowStock',
            fields=[
                ('supply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supply_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'medistock_v_low_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockVMonthlyConsumption',
            fields=[
                ('supply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.DateTimeField(blank=True, null=True)),
                ('supply_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tx_count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_v_monthly_consumption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockVPendingRequest',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_no', models.CharField(blank=True, max_length=255, null=True)),
                ('source_module', models.CharField(blank=True, max_length=100, null=True)),
                ('source_department', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.BigIntegerField(blank=True, null=True)),
                ('total_qty_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'medistock_v_pending_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockVStockCard',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_datetime', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('source_module', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'medistock_v_stock_card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockVStockSummary',
            fields=[
                ('supply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supply_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('main_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cart_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_v_stock_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedistockPurchaseRequest',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_no', models.CharField(max_length=30, unique=True)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('purchase_type', models.CharField(default='REGULAR', max_length=20)),
                ('pr_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FOR_APPROVAL', 'For Approval'), ('APPROVED', 'Approved'), ('ON_DELIVERY', 'On Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=120, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medistock_purchase_requests',
                'ordering': ['-pr_id'],
            },
        ),
        migrations.CreateModel(
            name='MedistockPurchaseRequestItem',
            fields=[
                ('pr_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medistock.medistockpurchaserequest')),
                ('supply', models.ForeignKey(db_column='supply_id', on_delete=django.db.models.deletion.DO_NOTHING, to='medistock.medistocksupplyitem')),
            ],
            options={
                'db_table': 'medistock_purchase_request_items',
            },
        ),
    ]
