# Generated by Django 6.0.3 on 2026-04-13 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('emergency_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('purok', models.CharField(blank=True, max_length=40, null=True)),
                ('barangay', models.CharField(blank=True, max_length=80, null=True)),
                ('city_municipal', models.CharField(blank=True, max_length=80, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('trail', models.CharField(blank=True, max_length=120, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_trail', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'patient_emergency_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpdServiceSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=10)),
                ('service_label', models.CharField(blank=True, max_length=80, null=True)),
                ('days_open', models.CharField(blank=True, max_length=40, null=True)),
                ('mon_open', models.TimeField(blank=True, null=True)),
                ('mon_close', models.TimeField(blank=True, null=True)),
                ('tue_open', models.TimeField(blank=True, null=True)),
                ('tue_close', models.TimeField(blank=True, null=True)),
                ('wed_open', models.TimeField(blank=True, null=True)),
                ('wed_close', models.TimeField(blank=True, null=True)),
                ('thu_open', models.TimeField(blank=True, null=True)),
                ('thu_close', models.TimeField(blank=True, null=True)),
                ('fri_open', models.TimeField(blank=True, null=True)),
                ('fri_close', models.TimeField(blank=True, null=True)),
                ('sat_open', models.TimeField(blank=True, null=True)),
                ('sat_close', models.TimeField(blank=True, null=True)),
                ('active_today', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_trail', models.CharField(blank=True, max_length=120, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opd_service_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProfiling',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_id', models.CharField(blank=True, max_length=8, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('ext', models.CharField(blank=True, max_length=5, null=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=5)),
                ('civil_status', models.CharField(max_length=5)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('purok', models.CharField(blank=True, max_length=40, null=True)),
                ('barangay', models.CharField(blank=True, max_length=80, null=True)),
                ('city_municipal', models.CharField(blank=True, max_length=80, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('smoker', models.BooleanField(default=False)),
                ('quitter', models.BooleanField(default=True)),
                ('sticks_per_day', models.IntegerField(blank=True, null=True)),
                ('trail', models.CharField(blank=True, max_length=120, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_trail', models.CharField(blank=True, max_length=120, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient_profiling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID of user who made the change')),
                ('username', models.CharField(help_text='Username of user who made the change', max_length=100)),
                ('user_fullname', models.CharField(help_text='Full name of user', max_length=200)),
                ('user_role', models.CharField(help_text='Role of user (OPD_CLERK, NURSE, etc.)', max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('RESTORE', 'Restored')], help_text='Type of action performed', max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Name of field that was changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before change')),
                ('new_value', models.TextField(blank=True, help_text='New value after change')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the change was made')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of user')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the change')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='opd.patientprofiling')),
            ],
            options={
                'db_table': 'patient_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', '-timestamp'], name='patient_aud_patient_dceacc_idx'), models.Index(fields=['user_id', '-timestamp'], name='patient_aud_user_id_2821e0_idx'), models.Index(fields=['action', '-timestamp'], name='patient_aud_action_a81942_idx')],
            },
        ),
    ]
