services:

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_DB: techcare_db
      POSTGRES_USER: techcareuser
      POSTGRES_PASSWORD: TechcarePCH@2026

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: django_backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000

    environment:
      DB_NAME: techcare_db
      DB_USER: techcareuser
      DB_PASSWORD: TechcarePCH@2026
      DB_HOST: db
      DB_PORT: 5432

    ports:
      - "8000:8000"

    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: techcarepch@gmail.com
      PGADMIN_DEFAULT_PASSWORD: TechcarePCH@2026

    ports:
      - "5050:80"

    depends_on:
      - db

volumes:
  postgres_data: