# Generated by Django 6.0.4 on 2026-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdRoomLocation',
            fields=[
                ('room_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('room_name', models.CharField(blank=True, max_length=80, null=True)),
                ('room_type', models.CharField(blank=True, max_length=30, null=True)),
                ('service', models.CharField(blank=True, max_length=30, null=True)),
                ('q_prefix', models.CharField(blank=True, max_length=2, null=True)),
                ('doctor_id', models.IntegerField(blank=True, null=True)),
                ('doctor_display', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trail', models.CharField(blank=True, max_length=120, null=True)),
                ('updated_trail', models.CharField(blank=True, max_length=120, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opd_room_location',
                'managed': False,
            },
        ),
    ]
