# Generated by Django 6.0.3 on 2026-04-03 03:55

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS pch.user_settings (
                    id SERIAL PRIMARY KEY,
                    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
                    push_notifications BOOLEAN NOT NULL DEFAULT TRUE,
                    dark_mode BOOLEAN NOT NULL DEFAULT FALSE,
                    language VARCHAR(3) NOT NULL DEFAULT 'en',
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    user_id INTEGER NOT NULL UNIQUE REFERENCES pch.users(user_id) ON DELETE CASCADE
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS pch.user_settings;"
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS user_settings_user_id_idx ON pch.user_settings(user_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS user_settings_user_id_idx;"
        ),
    ]
