# Generated by Django 6.0.4 on 2026-05-08 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('chief_nurse', 'Chief Nurse'), ('clerk', 'Clerk'), ('lab_tech', 'Laboratory Technician'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('kitchen_staff', 'Kitchen Staff'), ('social_worker', 'Social Worker'), ('inventory_manager', 'Inventory Manager'), ('patient', 'Patient')], default='clerk', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('fil', 'Filipino'), ('ceb', 'Bisaya')], default='en', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'Users Settings',
                'db_table': 'pch.user_settings',
            },
        ),
    ]
