# Generated by Django 6.0.4 on 2026-05-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyChargeSlip',
            fields=[
                ('charge_slip_id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_slip_no', models.CharField(max_length=30, unique=True)),
                ('rx_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('status', models.CharField(choices=[('FOR_BILLING', 'For Billing'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='FOR_BILLING', max_length=15)),
                ('billing_paid_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('trail', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'pharmacy_charge_slips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyChargeSlipItem',
            fields=[
                ('charge_slip_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'pharmacy_charge_slip_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyDispenseReceipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(max_length=30, unique=True)),
                ('ipd_dispensing_id', models.IntegerField(blank=True, null=True)),
                ('ipd_cart_form_id', models.IntegerField(blank=True, null=True)),
                ('admission_id', models.IntegerField(blank=True, null=True)),
                ('from_location_id', models.IntegerField(default=1)),
                ('dispensing_date', models.DateField(auto_now_add=True)),
                ('charge_slip_no', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20)),
                ('dispensed_by', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pharmacy_dispense_receipts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyDispenseReceiptItem',
            fields=[
                ('receipt_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=30)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('from_location_id', models.IntegerField(blank=True, null=True)),
                ('line_status', models.CharField(default='DISPENSED', max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmacy_dispense_receipt_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyGoodsReceipt',
            fields=[
                ('gr_id', models.AutoField(primary_key=True, serialize=False)),
                ('gr_no', models.CharField(max_length=30, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received')], default='RECEIVED', max_length=15)),
                ('verified_by', models.IntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmacy_goods_receipts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyGoodsReceiptItem',
            fields=[
                ('gr_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_ordered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expiry_date', models.DateField()),
                ('unit_cost_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmacy_goods_receipt_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyInventoryAdjustment',
            fields=[
                ('adj_id', models.AutoField(primary_key=True, serialize=False)),
                ('adj_type', models.CharField(choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('DISPOSED', 'Disposed'), ('COUNT_VARIANCE', 'Count Variance'), ('RETURN', 'Return')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trail', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'pharmacy_inventory_adjustments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyInventoryAdjustmentItem',
            fields=[
                ('adj_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'pharmacy_inventory_adjustment_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyMedicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('medicine_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pharmacy_medicines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=80, unique=True)),
                ('location_type', models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('CART', 'Cart')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pharmacy_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyPurchaseRequest',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_no', models.CharField(max_length=30, unique=True)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('purchase_type', models.CharField(choices=[('REGULAR', 'Regular'), ('EMERGENCY', 'Emergency')], default='REGULAR', max_length=10)),
                ('pr_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('ON_DELIVERY', 'On Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trail', models.CharField(blank=True, max_length=120, null=True)),
                ('updated_trail', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'pharmacy_purchase_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyPurchaseRequestItem',
            fields=[
                ('pr_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_by_module', models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('CENTRAL_SUPPLY', 'Central Supply')], max_length=20)),
                ('item_type', models.CharField(choices=[('MEDICINE', 'Medicine'), ('SUPPLY', 'Supply')], max_length=10)),
                ('medicine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('medistock_item_id', models.BigIntegerField(blank=True, null=True)),
                ('qty_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_snapshot', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmacy_purchase_request_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyStockBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=40)),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cost per unit for this specific batch', max_digits=12, null=True)),
            ],
            options={
                'db_table': 'pharmacy_stock_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacySupplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100, unique=True)),
                ('delivery_days_avg', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmacy_suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('TRANSFER', 'Transfer'), ('ADJUST', 'Adjust')], max_length=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('service_source', models.CharField(blank=True, choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('CART', 'Cart')], max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trail', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'pharmacy_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyInventoryBalance',
            fields=[
                ('medicine', models.ForeignKey(db_column='medicine_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='pharmacy.pharmacymedicine')),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'pharmacy_inventory_balance',
                'managed': False,
            },
        ),
    ]
