# Generated by Django 6.0.4 on 2026-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdPrescription',
            fields=[
                ('rx_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('ltr_main_keyctr', models.IntegerField(blank=True, null=True)),
                ('patient_id', models.IntegerField()),
                ('medicine_id', models.IntegerField(blank=True, null=True)),
                ('medicine_name_snapshot', models.CharField(blank=True, max_length=120, null=True)),
                ('dosage', models.CharField(blank=True, max_length=40, null=True)),
                ('frequency', models.CharField(blank=True, max_length=40, null=True)),
                ('duration', models.CharField(blank=True, max_length=40, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opd_prescription',
                'managed': False,
            },
        ),
    ]
