# Generated by Django 6.0.4 on 2026-05-21 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0002_opdprescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartForm',
            fields=[
                ('cart_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('requested_by', models.IntegerField()),
                ('requested_by_name', models.CharField(max_length=100)),
                ('from_location_id', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REPLENISHED', 'Replenished')], default='PENDING', max_length=20)),
                ('trail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ipd_cart_forms',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartFormItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_id', models.IntegerField(blank=True, null=True)),
                ('date_taken', models.DateField()),
                ('drug_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('administered_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ipd_cart_form_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispensingSheet',
            fields=[
                ('dispensing_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_time', models.TimeField(auto_now_add=True)),
                ('requested_by', models.IntegerField()),
                ('requested_by_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISPENSED', 'Dispensed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('dispensed_by', models.IntegerField(blank=True, null=True)),
                ('dispensed_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ipd_services_dispensing',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispensingSheetItem',
            fields=[
                ('dispensing_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_id', models.IntegerField(blank=True, null=True)),
                ('date_requested', models.DateField()),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pharmacist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ipd_services_dispensing_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpdCartInventory',
            fields=[
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='cart_inventory', serialize=False, to='pharmacy.pharmacymedicine')),
                ('qty_on_hand', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'pharmacy_inventory_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpdDepartments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_code', models.CharField(max_length=10, unique=True)),
                ('department_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipd_departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpdNoticeOfAdmission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_id', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admitting_impression', models.TextField(blank=True, db_column='admitting_impression', null=True)),
                ('bp', models.CharField(blank=True, max_length=20, null=True)),
                ('pr', models.CharField(blank=True, max_length=20, null=True)),
                ('temp', models.CharField(blank=True, max_length=20, null=True)),
                ('rr', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('o2_sat', models.CharField(blank=True, max_length=20, null=True)),
                ('admitting_physician', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ipd_notice_of_admission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpdRooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('bed_code', models.CharField(max_length=10)),
                ('room_type', models.CharField(max_length=20)),
                ('is_occupied', models.BooleanField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipd_rooms',
                'managed': False,
            },
        ),
    ]
