// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzSYpMD8I2mdCJCLf0Xum1wDM5MQ5EAQw',
    appId: '1:295590174995:web:8eade257ea8e896e523ae6',
    messagingSenderId: '295590174995',
    projectId: 'techcare-pch2026',
    authDomain: 'techcare-pch2026.firebaseapp.com',
    storageBucket: 'techcare-pch2026.firebasestorage.app',
    measurementId: 'G-QQ0VSB4KEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYRYrqwo3zzsD65HQLRGEYQQ_hAc_vUJs',
    appId: '1:295590174995:android:4660c01b6608de81523ae6',
    messagingSenderId: '295590174995',
    projectId: 'techcare-pch2026',
    storageBucket: 'techcare-pch2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-SFATwSzEItSva-cAS5RHuwA7Uwaq3U',
    appId: '1:295590174995:ios:239ff511b5ad1e05523ae6',
    messagingSenderId: '295590174995',
    projectId: 'techcare-pch2026',
    storageBucket: 'techcare-pch2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
